### ISSUE TITLE
如何对需要鉴权的页面进行XSS/CSRF检测？

### ISSUE THREAD

**Issue by glq2000** [zhuyingda/veneno#3]
请问，对于有的页面比如用户中心的各页面，用户在登录状态下才可以访问这些页面的功能和接口；
对于这类页面，veneno是如何进行扫描和检测 XSS/CSRF漏洞的？
或者veneno是否提供接口或配置文件，使得使用者可以配置veneno，使其获得登录状态？

**Comment by zhuyingda** [comment]
页面的session实际上是通过cookie维护的，目前最新的veneno中 两个xss模块都提供了cookie这个字段，你可以直接把登录状态的cookie复制到里面去。
具体调用方法，可以参考test目录下的xss_self.js 和 xss_dom.js
